### ISSUE TITLE
Same code but I am getting error.

### ISSUE THREAD

**Issue by dhruvdesmond** [Jordan141/YelpCamp#30]
`router.post("/campground/:id/comment",isLoggedIn,function(req,res){
    Campground.findById(req.params.id,function(err,campground){
        if(err){
            console.log(err);
        }else{
            
            
            Comment.create(req.body.comment,function(err,comment){
                if(err){
                    console.log(err);
                }
                else
                {
                    comment.author.id = req.user._id;
                    comment.author.username = req.user.username;
                    comment.save();
                    campground.comments.push(comment);
                    campground.save();
                    console.log(comment);
                    res.redirect("/campground/"+ campground._id);
                }
                
            });
        }
    });
});`

/home/ec2-user/environment/Websitedemo/v1.6/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: Cannot set property 'id' of undefined
    at /home/ec2-user/environment/Websitedemo/v1.6/routes/comment.js:34:39
    at Function.<anonymous> (/home/ec2-user/environment/Websitedemo/v1.6/node_modules/mongoose/lib/model.js:3953:16)
    at parallel (/home/ec2-user/environment/Websitedemo/v1.6/node_modules/mongoose/lib/model.js:2089:12)
    at /home/ec2-user/environment/Websitedemo/v1.6/node_modules/async/internal/parallel.js:35:9
    at /home/ec2-user/environment/Websitedemo/v1.6/node_modules/async/internal/once.js:12:16
    at iteratorCallback (/home/ec2-user/environment/Websitedemo/v1.6/node_modules/async/eachOf.js:52:13)
    at /home/ec2-user/environment/Websitedemo/v1.6/node_modules/async/internal/onlyOnce.js:12:16
    at /home/ec2-user/environment/Websitedemo/v1.6/node_modules/async/internal/parallel.js:32:13
    at apply (/home/ec2-user/environment/Websitedemo/v1.6/node_modules/lodash/_apply.js:15:25)
    at /home/ec2-user/environment/Websitedemo/v1.6/node_modules/lodash/_overRest.js:32:12
    at callbackWrapper (/home/ec2-user/environment/Websitedemo/v1.6/node_modules/mongoose/lib/model.js:2058:11)
    at /home/ec2-user/environment/Websitedemo/v1.6/node_modules/mongoose/lib/model.js:3953:16
    at model.$__save.error (/home/ec2-user/environment/Websitedemo/v1.6/node_modules/mongoose/lib/model.js:346:7)
    at /home/ec2-user/environment/Websitedemo/v1.6/node_modules/kareem/index.js:297:21
    at next (/home/ec2-user/environment/Websitedemo/v1.6/node_modules/kareem/index.js:209:27)
    at Kareem.execPost (/home/ec2-user/environment/Websitedemo/v1.6/node_modules/kareem/index.js:217:3)

**Comment by Jordan141** [comment]
Hey, could you upload your code to a repository somewhere for me to take a look at? Seems your id isn't getting through to where it should be, which leads me to believe the error is elsewhere.
